# Generated by Django 3.0.4 on 2020-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlwithcredentials',
            name='full_url',
            field=models.URLField(),
        ),
    ]
