# Generated by Django 3.0.4 on 2020-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_api', '0002_auto_20200603_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlwithcredentials',
            name='url_hash',
            field=models.URLField(),
        ),
    ]
